### PR TITLE
#30 - Added hierarchy of using a specific .eslintrc* file, based on: …

### PR DESCRIPTION
**Pull request by Chris2011**
…https://eslint.org/docs/user-guide/configuring#configuration-file-formats.

Config in package.json is out of scope of this PR. See #30

### CODE REVIEW

**Comment by Chris2011** [comment]
So now I removed some code, refactored a bit and added a new checkbox to use a project based config file instead of a custom one. The rest is done via the eslint cli. If there is no --config param, it will do the hierarchical logic by its own. So no need to add it by myself. Please have a look and merge :)

**Comment by Chris2011** [comment]
Also, the hierarchy will work until the last config file, that means package.json (eslintConfig: {}) is also supported if there is nothing else.

**Review by joakim-eriksson — APPROVED** [review]
Looks good

**Comment by Chris2011** [comment]
Can you please add the label "hacktoberfest-accepted" to this PR? That would be great :)

**Pull request merged**
